# Generated by Django 3.2.15 on 2023-01-14 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_profile_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='author',
        ),
    ]
