# Generated by Django 3.2.15 on 2022-09-13 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_auto_20220913_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='author',
        ),
    ]
