# Generated by Django 3.2.15 on 2022-09-13 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0004_rating_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='author',
        ),
    ]
