# Generated by Django 3.2.15 on 2022-09-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0006_rating_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='five',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='four',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='one',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='three',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='two',
        ),
        migrations.AddField(
            model_name='rating',
            name='rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
