# Generated by Django 3.2.15 on 2022-09-20 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0007_auto_20220913_1544'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['-created_date']},
        ),
    ]
