# Generated by Django 3.2.15 on 2022-10-24 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(choices=[('pick', 'Please Choose an Option'), ('se', 'Space Engineers'), ('mc', 'Minecraft')], default='pick', max_length=40)),
                ('server_name', models.TextField(max_length=50)),
                ('server_address', models.GenericIPAddressField(unpack_ipv4=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('banner', models.ImageField(blank=True, default='../default_server_banner_hfurfy', null=True, upload_to='images/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
