# Generated by Django 3.2.15 on 2022-11-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='banner',
            field=models.ImageField(blank=True, default='../default_server_banner_hfurfy', upload_to='images/'),
        ),
    ]
