# Generated by Django 3.2.15 on 2022-09-20 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_alter_server_server_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='game',
            field=models.CharField(choices=[('se', 'Space Engineers'), ('mc', 'Minecraft')], default='se', max_length=40),
            preserve_default=False,
        ),
    ]
