# Generated by Django 3.2.15 on 2022-09-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0003_server_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='game',
            field=models.CharField(choices=[('pick', 'Please Choose an Option'), ('se', 'Space Engineers'), ('mc', 'Minecraft')], default='pick', max_length=40),
        ),
    ]
