# Generated by Django 3.2.15 on 2022-10-18 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0004_alter_server_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='banner',
            field=models.ImageField(blank=True, default='../default_server_banner_hfurfy', null=True, upload_to='images/'),
        ),
    ]
