# Generated by Django 3.2.15 on 2022-09-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='video',
            field=models.FileField(blank=True, upload_to='videos/', verbose_name=''),
        ),
    ]
